config/routes.rb
Hector::Application.routes.draw do
  # post "drops/create"

  resources :dropzones do
	  resources :drops
	end

  get "dropbox/authorize"
  get "dropbox/authorized_callback"
  get "dropbox/create_user_and_return_home"
  get "dropbox/index"
  get "dropbox/upload"

  devise_for :users, :controllers => { :registrations => "users/registrations" }

  root 'dropbox#index'
end

app/models/drop.rb
class Drop
  include Mongoid::Document
  # attr_accessible :drop_file, :drop_file_cache
  # mount_uploader :drop_file, DropUploader
  mount_uploader :drop, DropUploader, mount_on: :drop_filename
  embedded_in :dropzone
end

app/models/dropzone.rb
class Dropzone
  include Mongoid::Document
  field :name, type: String
  belongs_to :user
  embeds_many :drops
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Custom fields
  field :dropbox_token, :type => String, :default => "token"
  field :dropbox_secret, :type => String, :default => "secret"
  has_many :dropzones
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # protected

  # def devise_parameter_sanitizer
  #   if resource_class == User
  #     User::ParameterSanitizer.new(User, :user, params)
  #   else
  #     super # Use the default one
  #   end
  # end
end

app/controllers/dropbox_controller.rb
class DropboxController < ApplicationController
def authorize
    consumer = Dropbox::API::OAuth.consumer(:authorize)
    request_token = consumer.get_request_token
    session[:request_token] = request_token.token
    session[:request_token_secret] = request_token.secret
    redirect_to request_token.authorize_url(:oauth_callback => 'http://localhost:3000/dropbox/authorized_callback')
  end

  def authorized_callback
    consumer = Dropbox::API::OAuth.consumer(:authorize)
    request_token = OAuth::RequestToken.new(consumer, session[:request_token], session[:request_token_secret])
    if params[:not_approved] == "true"
      flash[:error] = "Oops! Looks like you didn't complete authentication with Dropbox."
      redirect_to root_url
    else
      result = request_token.get_access_token(oauth_verifier: params[:oauth_token])

      session[:token] = result.token
      session[:secret] = result.secret

      client = Dropbox::API::Client.new :token => session[:token], :secret => session[:secret]
      session[:email] = client.account.email

      redirect_to new_user_registration_url
    end
  end

  # def create_user_and_return_home(result)

  # 	puts "result.token: #{result.token}"
  # 	puts "result.secret: #{result.secret}"


  #   if user = User.find_by_dropbox_uid(params[:uid])
  #     user.update_attributes(access_token: result.token, access_secret: result.secret)
  #     if user.waitlist
  #       flash[:notice] = "Success!"
  #       redirect_to controller: 'home', action: 'show', id: user.id
  #     else
  #       flash[:notice] = "Success!"
  #       redirect_to controller: 'home', action: 'show', id: user.id
  #     end
  #   else
  #     user = User.create!(access_token: result.token, access_secret: result.secret, dropbox_uid: params[:uid])
  #     flash[:notice] = "Beauty! You've succesfully authorized Splashbox with Dropbox."
  #     redirect_to controller: 'home', action: 'show', id: user.id
  #   end
  # end

  def index
    @user = current_user
  end

  def upload
  end
end

app/controllers/drops_controller.rb
class DropsController < ApplicationController


  # POST /drops
  # POST /drops.json
  def create
    @dropzone = Dropzone.find(drop_params[:dropzone])

    # @dropzone.drops = [ Drop.new(drop_params[:drop_filename]) ]
    # @dropzone.drops.new(drop_filename: "Violator!")
    @drop = @dropzone.drops.new drop: drop_params[:drop]

    respond_to do |format|
      if @drop.save
        format.html { redirect_to @dropzone, notice: 'Drop was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dropzone }
        DropboxWorker.perform_async(current_user._id.to_s, @dropzone._id.to_s, @drop._id.to_s)
      else
        format.html { render action: 'new' }
        format.json { render json: @dropzone.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def drop_params
      params.require(:drop).permit(:attachment, :drop, :drops, :attachments, :dropzone, :_id, :_id_cache, :drop_filename, :drop_cache, :filename, :drop_file)
    end
end

app/controllers/dropzones_controller.rb
class DropzonesController < ApplicationController
  before_action :set_dropzone, only: [:show, :edit, :update, :destroy]

  # GET /dropzones
  # GET /dropzones.json
  def index
    @dropzones = Dropzone.all
  end

  # GET /dropzones/1
  # GET /dropzones/1.json
  def show
    @drop = Drop.new
  end

  # GET /dropzones/new
  def new
    @dropzone = Dropzone.new
  end

  # GET /dropzones/1/edit
  def edit
  end

  # POST /dropzones
  # POST /dropzones.json
  def create
    @dropzone = Dropzone.new(dropzone_params)

    respond_to do |format|
      if @dropzone.save
        format.html { redirect_to @dropzone, notice: 'Dropzone was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dropzone }
      else
        format.html { render action: 'new' }
        format.json { render json: @dropzone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dropzones/1
  # PATCH/PUT /dropzones/1.json
  def update
    respond_to do |format|
      if @dropzone.update(dropzone_params)
        format.html { redirect_to @dropzone, notice: 'Dropzone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dropzone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dropzones/1
  # DELETE /dropzones/1.json
  def destroy
    @dropzone.destroy
    respond_to do |format|
      format.html { redirect_to dropzones_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dropzone
      @dropzone = Dropzone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dropzone_params
      params.require(:dropzone).permit(:name).merge(:user => current_user)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def sign_up_params
  	params.require(:user).permit(:email, :password, :password_confirmation).merge(:dropbox_token => session[:token], :dropbox_secret => session[:secret])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dropbox_helper.rb
module DropboxHelper
end

app/helpers/drops_helper.rb
module DropsHelper
end

app/helpers/dropzones_helper.rb
module DropzonesHelper
end

app/views/dropbox/authorize.html.haml
%h1 Dropbox#authorize
%p Find me in app/views/dropbox/authorize.html.haml

app/views/dropbox/authorized_callback.html.haml
%h1 Dropbox#authorized_callback
%p Find me in app/views/dropbox/authorized_callback.html.haml

app/views/dropbox/create_user_and_return_home.html.haml
%h1 Dropbox#create_user_and_return_home
%p Find me in app/views/dropbox/create_user_and_return_home.html.haml

app/views/dropbox/index.html.haml
- if user_signed_in?
	= current_user.email
	%br/
	%ul
		- @user.dropzones.each do |dropzone|
			%li= link_to dropzone.name, dropzone
- else
	no current user


%p= link_to "Sign out", destroy_user_session_path, :method => :delete

app/views/dropbox/upload.html.haml
%h1 Dropbox#upload
%p Find me in app/views/dropbox/upload.html.haml

app/views/drops/create.html.haml
%h1 Drops#create
%p Find me in app/views/drops/create.html.haml

app/views/dropzones/_form.html.haml
= form_for @dropzone do |f|
  - if @dropzone.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dropzone.errors.count, "error")} prohibited this dropzone from being saved:"
      %ul
        - @dropzone.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/dropzones/edit.html.haml
%h1 Editing dropzone

= render 'form'

= link_to 'Show', @dropzone
\|
= link_to 'Back', dropzones_path

app/views/dropzones/index.html.haml
%h1 Listing dropzones

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @dropzones.each do |dropzone|
    %tr
      %td= dropzone.name
      %td= link_to 'Show', dropzone
      %td= link_to 'Edit', edit_dropzone_path(dropzone)
      %td= link_to 'Destroy', dropzone, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Dropzone', new_dropzone_path

app/views/dropzones/new.html.haml
%h1 New dropzone

= render 'form'

= link_to 'Back', dropzones_path

app/views/dropzones/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @dropzone.name

= link_to 'Edit', edit_dropzone_path(@dropzone)
\|
= link_to 'Back', dropzones_path


= form_for [@dropzone, Drop.new], :html => {:multipart => true} do |f|
  %p
    <label>My Avatar</label>
    = f.file_field :drop
    = f.hidden_field :drop_cache
    = f.text_field :dropzone, :value => @dropzone._id

    = f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hector</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>